// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uttifordgqatrkjvkfzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dGlmb3JkZ3FhdHJranZrZnptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTE5NzYsImV4cCI6MjA1OTk2Nzk3Nn0.VLSzdJd2uIKGvuD--DiuvbEk1DsOJ7Ab7XulriAJnDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);